name: "Recipe"
description: "Create a new recipe"
labels: ["✅ Needs writing-up","✅ Requires pictures","👋 Haven't cooked"]
body:
        
  - type: textarea
    id: remarks
    attributes:
      label: "Introduction"
      description: "Share background information about this recipe and a example picture."
      render: markdown
    validations:
      required: false
      
  - type: markdown
    attributes:
      value: |
        ## Ingredients
        
  - type: textarea
    id: ingredients
    attributes:
      label: "Ingredients"
      description: "Provide a list of the ingredients."
      value: "- "
    validations:
      required: true 

  - type: textarea
    id: method
    attributes:
      label: "Method"
      description: "List the steps involved in this recipe."
      value: "1. "
    validations:
      required: true 
      
  - type: input
    id: source
    attributes:
      label: "Source"
      description: "Record any URL to the recipe"
    validations:
      required: false
