name: Generate calendar from project

# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idconcurrency
# concurrency: 
#   group: ${{ github.ref }}
#   cancel-in-progress: true

on:
  workflow_dispatch:
#   schedule:
#     - cron: '1 0 * * *'
  project_card: 
    types: [created, moved, converted, edited, deleted]
  project_column:
    types: [created, updated, moved, deleted]

jobs:

  build:
    name: Build and Generate ICS file
    runs-on: ubuntu-latest
    env:
      ICS_PATH: ${{ github.workspace }}/resources/MealPlanner.ics
      
    steps:

    - name: Check-out repository
      uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9    

    - name: Install Python dependencies
      run: pip install -Uq PyGithub
      
    - name: Generate ICS file
      run: python .github/scripts/generateics.py
      env:
        CONTEXT_GITHUB: ${{ toJson(github) }}
      
    - name: Upload ICS to blog
      uses: danhendrickson/sftp-transfer-action@v1.23
      with:
        server: ${{ secrets.blog_sftp_address }}
        user: ${{ secrets.blog_sftp_username }}
        pass: ${{ secrets.blog_sftp_password}}
        port: ${{ secrets.blog_sftp_port }}
        local-path: ${{ env.ICS_PATH }}
        remote-path: "/MealPlanner.ics"
