name: Publish recipe

# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency
# concurrency: 
#   group: ${{ github.ref }}
#   cancel-in-progress: true
  
on:
  workflow_dispatch:
  issues:
    types: [edited, closed, labeled, unlabeled]
  
jobs:

  build:
    name: Run python script
    runs-on: ubuntu-latest

    if: contains(github.event.issue.labels.*.name,'⚙ Trigger Published')
    
    steps:

    - name: Check-out repository
      uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9    

    - name: Install Python dependencies
      run: pip install -Uq PyGithub
      
    - name: Generate recipe markdown file
      run: python .github/scripts/publishrecipe.py
      env:
        CONTEXT_GITHUB: ${{ toJson(github) }}
